# Файл docker-compose.yml

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер селеноида
  selenoid:
    # Из какого образа запустить контейнер:
    image: "aerokube/selenoid"
    # Как назвать контейнер:
    container_name: selenoid
    # Порты для работы:
    ports:
      - "4444:4444"
    # Настройка сети для взаимодействия контейнеров
    networks:
      - selenoid
    # Какой volume подключить для этого контейнера
    volumes:
      - "./config.json:/etc/selenoid/config.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [ "-conf", "/etc/selenoid/config.json", "-container-network", "selenoid" ]


  test_docker:
    build: .
    container_name: test_docker
    depends_on:
      - selenoid
    networks:
      - selenoid
    tty: true
    command: [ "pytest" ]

  networks:
    selenoid:
      name: selenoid